import React from "react";
import Grid from "@mui/material/Grid";
import { Swap } from "./Swap";
import { Mint } from "./Mint";
import { Balances } from "./Balances";
import { ProvideLiquidity } from "./ProvideLiquidity";
import Head from "next/head";

interface SEOProps {
  title: string;
  description?: string;
}

export default function SEO({ title, description }: SEOProps) {
  return (
    <Head>
      <title>{title}</title>
      <meta
        name="description"
        content={description ?? "Generated by create next app"}
      />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
}
